### ISSUE TITLE
ActsInRelation::MissingRoleError というエラーが出ました。

### ISSUE THREAD

**Issue by nyuta01** [kami30k/acts_as_relationship#3]
➜  git:(master) ✗ rails s

```
=> Booting WEBrick
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/acts_in_relation-0.2.2/lib/acts_in_relation/core.rb:44:in `acts_in_relation': ActsInRelation::MissingRoleError (ActsInRelation::MissingRoleError)
  from test_app/app/models/user.rb:8:in `<class:User>'
  from test_app/app/models/user.rb:1:in `<top (required)>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `load'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `block in load_file'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:456:in `load_file'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:354:in `require_or_load'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:494:in `load_missing_constant'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `const_get'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:261:in `block in constantize'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `each'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `inject'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:259:in `constantize'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:566:in `get'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:597:in `constantize'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise.rb:292:in `get'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise/mapping.rb:81:in `to'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise/mapping.rb:76:in `modules'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise/mapping.rb:93:in `routes'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise/mapping.rb:160:in `default_used_route'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise/mapping.rb:70:in `initialize'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise.rb:326:in `new'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise.rb:326:in `add_mapping'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise/rails/routes.rb:238:in `block in devise_for'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise/rails/routes.rb:237:in `each'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.5/lib/devise/rails/routes.rb:237:in `devise_for'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise_token_auth-0.1.37/lib/devise_token_auth/rails/routes.rb:25:in `mount_devise_token_auth_for'
  from test_app/config/routes.rb:3:in `block in <top (required)>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:412:in `draw'
  from test_app/config/routes.rb:1:in `<top (required)>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `each'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:16:in `reload!'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:26:in `block in updater'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `call'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `execute'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:27:in `updater'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
  from test_app/config/environment.rb:5:in `<top (required)>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
  from test_app/config.ru:3:in `block in <main>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  from test_app/config.ru:in `new'
  from test_app/config.ru:in `<main>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/server.rb:61:in `app'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/server.rb:139:in `log_to_stdout'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/server.rb:78:in `start'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:80:in `block in server'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
  from test_app/bin/rails:9:in `require'
  from test_app/bin/rails:9:in `<top (required)>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/client/rails.rb:28:in `load'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/client/rails.rb:28:in `call'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/client/command.rb:7:in `call'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/client.rb:28:in `run'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.6.2/bin/spring:49:in `<top (required)>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/binstub.rb:11:in `load'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/binstub.rb:11:in `<top (required)>'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from User/user_name/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from test_app/bin/spring:13:in `<top (required)>'
  from bin/rails:3:in `load'
  from bin/rails:3:in `<main>'

```

**Comment by zenizh** [comment]
@andoromeda `:role` が指定されていないことが原因だと考えられます。
`acts_in_relation` メソッドはどのように呼び出していますか？
ref: https://github.com/kami-zh/acts_in_relation/blob/master/lib/acts_in_relation/core.rb#L44

**Comment by nyuta01** [comment]
動かしてたプロジェクトを消してしまったので、同じではないかもですが確かめてみます

**Comment by zenizh** [comment]
問題が確認できた際にissueを開けていただければまた対応できるかと思います :)
